package com.securescan.backend.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.securescan.backend.dto.WebsiteScanResponse;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@Service
public class PdfReportService {

    public byte[] generateWebsiteReport(WebsiteScanResponse report) {

        try {

            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

            Document document = new Document(PageSize.A4);

            PdfWriter.getInstance(document, outputStream);

            document.open();

            Font titleFont = new Font(
                    Font.HELVETICA,
                    22,
                    Font.BOLD,
                    new Color(0, 102, 204)
            );

            Font headingFont = new Font(
                    Font.HELVETICA,
                    14,
                    Font.BOLD
            );

            Font textFont = new Font(
                    Font.HELVETICA,
                    12,
                    Font.NORMAL
            );

            Paragraph title = new Paragraph(
                    "SecureScan AI\nWebsite Security Report",
                    titleFont
            );

            title.setAlignment(Element.ALIGN_CENTER);

            document.add(title);

            document.add(new Paragraph(" "));

            Paragraph date = new Paragraph(
                    "Generated On : " +
                            LocalDateTime.now().format(
                                    DateTimeFormatter.ofPattern(
                                            "dd-MM-yyyy HH:mm:ss"
                                    )
                            ),
                    textFont
            );

            document.add(date);

            document.add(new Paragraph(" "));

            PdfPTable table = new PdfPTable(2);

            table.setWidthPercentage(100);

            table.setWidths(new float[]{3,5});

            addRow(table,"Website",report.getWebsite());
            addRow(table,"SSL Certificate",report.getSsl());
            addRow(table,"HTTPS",report.getHttps());
            addRow(table,"DNS",report.getDns());
            addRow(table,"Security Headers",report.getHeaders());
            addRow(table,"Risk",report.getRisk());
            addRow(table,"Security Score",report.getScore()+"/100");

            document.add(table);

            document.add(new Paragraph(" "));

            Paragraph footer = new Paragraph(
                    "Generated by SecureScan AI",
                    headingFont
            );

            footer.setAlignment(Element.ALIGN_CENTER);

            document.add(footer);

            document.close();

            return outputStream.toByteArray();

        }

        catch (Exception e){

            throw new RuntimeException(
                    "Unable to generate PDF : " +
                            e.getMessage()
            );

        }

    }

    private void addRow(
            PdfPTable table,
            String key,
            String value
    ){

        PdfPCell c1 = new PdfPCell(
                new Phrase(key)
        );

        c1.setBackgroundColor(
                new Color(220,230,250)
        );

        table.addCell(c1);

        table.addCell(value);

    }

    private void addRow(
            PdfPTable table,
            String key,
            int value
    ){

        addRow(
                table,
                key,
                String.valueOf(value)
        );

    }

}